import type { CommandDefinition } from "./types.ts";

export const COMMAND_DEFINITIONS: CommandDefinition[] = [
  {
    name: "openagents-audit",
    description: "Security audit of a file, module, or API surface",
    agent: "nemesis",
    routeKind: "readonly",
    promptTemplate: "Mission: perform a security-focused audit with file:line evidence and concrete fixes. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTarget:",
  },
  {
    name: "openagents-debug",
    description: "Investigate a failure without drifting into implementation",
    agent: "hermes",
    routeKind: "readonly",
    promptTemplate: "Mission: investigate the failure path and identify the strongest verified root cause without editing. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nFailure:",
  },
  {
    name: "openagents-document",
    description: "Generate or update documentation",
    agent: "calliope",
    routeKind: "readonly",
    promptTemplate: "Mission: update documentation to match actual code behavior. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTarget:",
  },
  {
    name: "openagents-explore",
    description: "Map architecture, entrypoints, and ownership of a target",
    agent: "hermes",
    routeKind: "readonly",
    promptTemplate: "Mission: map entrypoints, abstractions, neighboring modules, and likely change points. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTarget:",
  },
  {
    name: "openagents-implement",
    description: "Implement a feature from a spec",
    agent: "hephaestus",
    routeKind: "edit-required",
    promptTemplate: "Mission: implement the requested production change from the specification. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nSpec:",
  },
  {
    name: "openagents-orchestrate",
    description: "Coordinate multi-step delivery across roles",
    agent: "odysseus",
    routeKind: "edit-required",
    promptTemplate: "Mission: coordinate multi-step delivery with bounded ownership and validation gates. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTask:",
  },
  {
    name: "openagents-plan-feature",
    description: "Break down a feature into tasks",
    agent: "athena",
    routeKind: "readonly",
    promptTemplate: "Mission: break the feature into concrete implementation tasks and acceptance gates. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nFeature:",
  },
  {
    name: "openagents-plan-refactor",
    description: "Plan a refactoring with impact analysis",
    agent: "athena",
    routeKind: "readonly",
    promptTemplate: "Mission: plan the refactor with target ownership, removed legacy surfaces, and validation gates. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nRefactoring:",
  },
  {
    name: "openagents-review",
    description: "Perform code review on a file or path",
    agent: "nemesis",
    routeKind: "readonly",
    promptTemplate: "Mission: review correctness, security, performance, style, missing validation, and prompt-contract drift. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTarget:",
  },
  {
    name: "openagents-test",
    description: "Execute test suite, analyze results",
    agent: "atalanta",
    routeKind: "execution-required",
    promptTemplate: "Mission: run tests, analyze failures, and identify root cause. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nScope:",
  },
  {
    name: "openagents-trace",
    description: "Trace a symbol, dependency edge, or data flow",
    agent: "hermes",
    routeKind: "readonly",
    promptTemplate: "Mission: trace a symbol, file, interface, dependency edge, or data flow end-to-end. Required workflow: inspect repo evidence first, execute the route contract, validate or report a concrete blocker. Reference parity: When exact parity, 1:1 behavior, source behavior, reference behavior, or image-backed matching is requested, inspect the reference first and preserve observable source behavior. Source behavior overrides agent taste, platform-native reinterpretation, inferred best practice, simplification, and approximation. No-hedge contract: Do not shrink the task, leave future-work notes, use approximation wording, or replace execution with advice. Finish the requested work or return the structured blocker. Blocker contract: If blocked, report BLOCKED, Attempted, Evidence, and Need with concrete details.\n\nTarget:",
  },
];
